### ISSUE TITLE
"Get new widgets" feature does not work

### ISSUE THREAD

**Issue by lucasrunner** [blue-systems/netrunner-15-issues#11]
When I click on "Get new widgets" > Download new plasma widgets, Plasma Addon - Installer window pops out and offers installing random content from "opendesktop.org" http://wstaw.org/m/2015/02/18/widget1.png Some items are clearly spam.

**Comment by star-buck** [comment]
this is kde-look, nothing we can do.

**Comment by lucasrunner** [comment]
Well you can remove "Get new widgets" button from the plasma widget explorer and this is my suggestion

**Comment by star-buck** [comment]
This would be a "feature-request" in KDE Plasma, Netrunner is not going to remove this on its own, therefore stays closed.

**Comment by lucasrunner** [comment]
Ok
